# Generated by Django 5.2.12 on 2026-03-18 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('step', models.CharField(choices=[('accueil', 'Accueil'), ('menu', 'Menu'), ('choix', 'Choix'), ('quantité', 'Quantité'), ('localisation', 'Localisation'), ('confirmation', 'Confirmation')], default='accueil', max_length=20)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
