# Generated by Django 5.2.12 on 2026-03-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='step',
            field=models.CharField(choices=[('accueil', 'Accueil'), ('menu', 'Menu'), ('choix', 'Choix'), ('quantite', 'Quantité'), ('localisation', 'Localisation'), ('confirmation', 'Confirmation')], default='accueil', max_length=20),
        ),
    ]
